let b = 2;

try{

let a = 2 + b;

}catch(err){
    console.log(err);
}finally{
    console.log("Executou");
}